name: tradepulse
channels:
  - conda-forge
  - apple
dependencies:
  - python=3.12
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - plotly>=5.15.0
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - statsmodels>=0.14.0
  - duckdb>=0.9.0
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0
  - pyzmq>=25.0.0
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - flake8>=6.0.0
  - black>=23.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - pip
  - pip:
    - mplfinance>=0.12.0
    - plyer>=2.1.0
    - backtrader>=1.9.76
    - nltk>=3.8.1
    - transformers>=4.30.0
    - alpaca-py>=0.13.0
    - boto3>=1.28.0
    - pyjwt>=2.8.0
    - tensorflow-macos>=2.13.0
    - prophet>=1.1.4
    - arch>=6.2.0
    - lightgbm>=4.0.0
