name: tradepulse
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and Data Science
  - python=3.10
  - pandas>=2.3.0
  - numpy>=2.2.0
  - matplotlib>=3.7.0
  - plotly>=6.0.0
  - scikit-learn>=1.3.0
  - scipy>=1.10.0
  
  # Machine Learning and AI
  - xgboost>=2.0.0
  - lightgbm>=4.1.0
  - statsmodels>=0.14.0
  - prophet>=1.1.4
  - transformers>=4.35.0
  - arch>=6.2.0
  
  # Database and Data Management
  - duckdb>=0.9.0
  - sqlalchemy>=2.0.0
  - pyarrow>=12.0.0
  - openpyxl>=3.1.0
  
  # Messaging and Communication
  - pyzmq>=25.0.0
  - requests>=2.31.0
  
  # Visualization and Charts
  - mplfinance>=0.12.0
  - seaborn>=0.13.0
  - bokeh>=3.7.0
  
  # Financial and Trading
  - yfinance>=0.2.0
  - ta>=0.10.0
  - backtrader>=1.9.76
  - alpaca-py>=0.13.0
  
  # Natural Language Processing
  - nltk>=3.8.1
  - textblob>=0.17.1
  - vaderSentiment>=3.3.2
  
  # Security and Authentication
  - python-dotenv>=1.0.0
  - pyjwt>=2.8.0
  - cryptography>=41.0.0
  - passlib>=1.7.4
  
  # Development and Testing
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.12.0
  - flake8>=6.1.0
  - black>=23.11.0
  - isort>=5.12.0
  - mypy>=1.7.0
  
  # Panel UI Framework (Core)
  - panel>=1.7.5
  - param>=1.13.0
  
  # Performance and Optimization
  - numba>=0.58.0
  - cython>=3.0.0
  
  # Jupyter and Development Environment
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - jupyterlab>=4.0.0
  
  # Utilities
  - pip
  - pip:
    # FastAPI Integration (V10.12)
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - aiohttp>=3.9.0
    - httpx>=0.25.0
    
    # Additional ML and AI packages
    - torch>=2.1.0
    - torchvision>=0.16.0
    - torchaudio>=2.1.0
    - optuna>=3.4.0
    - mlflow>=2.7.0
    
    # Advanced Financial Analysis
    - empyrical>=0.5.5
    - pyfolio>=0.9.2
    - riskfolio>=0.1.0
    
    # Real-time Data and APIs
    - websocket-client>=1.6.0
    - asyncio-mqtt>=0.13.0
    
    # Enhanced Visualization
    - plotly-express>=0.4.1
    - dash>=2.14.0
    - dash-bootstrap-components>=1.5.0
    
    # Data Processing and Analysis
    - polars>=0.19.0
    - vaex>=4.17.0
    - dask>=2023.10.0
    
    # Multi-format Data Support (V10.12)
    - feather-format>=0.4.1
    - h5py>=3.10.0
    - tables>=3.8.0
    
    # Monitoring and Logging
    - structlog>=23.2.0
    - prometheus-client>=0.19.0
    
    # Testing and Quality
    - hypothesis>=6.88.0
    - coverage>=7.3.0
    - tox>=4.11.0
    
    # Documentation
    - sphinx>=7.2.0
    - sphinx-rtd-theme>=1.3.0
    
    # Additional Dependencies for V10.12
    - python-dateutil>=2.8.2
    - typing-extensions>=4.0.0
    - pydantic>=2.0.0
    - plyer>=2.1.0
    
    # Cloud and Infrastructure
    - boto3>=1.28.0
    - docker>=6.1.0
    
    # Enhanced Data Access (V10.12)
    - pathlib2>=2.3.7
    - glob2>=0.7
    
    # Advanced ML and AI (V10.12)
    - tensorflow-macos>=2.13.0
    
    # Real-time Processing
    - asyncio-mqtt>=0.13.0
    
    # Enhanced Security
    - bcrypt>=4.0.0
    - argon2-cffi>=21.3.0
    
    # API Development Tools
    - pydantic-settings>=2.0.0
    - python-multipart>=0.0.6
    - email-validator>=2.0.0
    
    # Background Tasks
    - celery>=5.3.0
    - redis>=5.0.0
    
    # File Upload and Processing
    - python-magic>=0.4.27
    - Pillow>=10.0.0
    
    # Enhanced Error Handling
    - sentry-sdk>=1.38.0
    
    # Performance Monitoring
    - psutil>=5.9.0
    - memory-profiler>=0.61.0
    
    # Advanced Testing
    - pytest-asyncio>=0.21.0
    - pytest-mock>=3.12.0
    - factory-boy>=3.3.0
    
    # Code Quality
    - pre-commit>=3.5.0
    - bandit>=1.7.5
    
    # Development Tools
    - ipython>=8.17.0
    - jupyter-contrib-nbextensions>=0.5.1
