name: tradepulse-fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and data processing
  - python=3.10
  - pandas=2.1.4
  - numpy=1.25.2
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  
  # HTTP and networking
  - requests
  - python-dateutil
  - pytz
  
  # Development tools
  - jupyter
  - ipython
  
  # Pip packages (not available in conda-forge)
  - pip
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.35.0
    - python-multipart==0.0.20
    - python-dotenv==1.1.1
    - aiohttp==3.12.15
    - httpx==0.28.1
    - websockets==15.0.1
    - plotly==5.17.0
    - yfinance==0.2.28
    - alpha-vantage==2.3.1
    - iexfinance==0.5.0
    - redis==5.0.1
    - sqlalchemy==2.0.23
    - alembic==1.13.1
    - psycopg2-binary==2.9.9
    - panel==1.7.5
    - bokeh>=3.5.0,<3.8.0
    - duckdb==0.9.2
    - h5py==3.10.0
    - pyarrow==14.0.2
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - pytest-cov==4.1.0
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.1
